### ISSUE TITLE
Develop a standard process for how they post content in github

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#56]
Also figure out the best way to share work with 18F and FEC teams.

**Comment by jenniferthibault** [comment]
@noahmanger here's the summary of what I got down from earlier, please edit!

Proposed new process:
- [x]  Put all in-progress design files on InVision under "FEC Design" » "source files" » "in-progress" and use as a working server. Save all active and previous design work here
- [x]  When a design is ready for review, export the screens to the top level so that they are find-able by InVision. If it needs small feedback, share the link with the partners slack channel
- [x]  Plan a weekly standing meeting  w/ FEC partners and design stakeholders  (need @leahbannon 's help w/ this) to review weekly progress and have time for more detailed design feedback. This meeting would be best over video conference, so that FEC doesn't have to go to GSA, and it can happen without much support from other team members.
- [x]  Link all InVision screens to the active GitHub repo

backlog:
- [x]  Consolidate Sketch design files so there aren't duplicates

**Comment by noahmanger** [comment]
Sounds good! I'll get my files in there tonight.
