### ISSUE TITLE
Design and implement mobile/tablet header & nav

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-alpha#65]
@noahmanger here are some mockups for various scenarios. Sorry it's a lot, glad to talk through any questions!
### Tablet:

![tablet option 2](https://cloud.githubusercontent.com/assets/11636908/9528047/ac404e80-4cc0-11e5-858e-fba4e1e82035.png)
### Tablet expanded:

![tablet portrait copy 2](https://cloud.githubusercontent.com/assets/11636908/9528049/b0316ef2-4cc0-11e5-9e8c-1000d5a75b28.png)
### Mobile w/ footer:

![mobile portrait](https://cloud.githubusercontent.com/assets/11636908/9528243/93f5eb72-4cc1-11e5-92cb-252ed45c7df0.png)
### Mobile expanded:

![mobile portrait copy](https://cloud.githubusercontent.com/assets/11636908/9528065/c49eb840-4cc0-11e5-9466-b6a34a289462.png)
### Mobile sub-nav:

![mobile portrait copy 2](https://cloud.githubusercontent.com/assets/11636908/9528068/c83f07f2-4cc0-11e5-88b8-1e59f046fb5f.png)
### Full header w/ breadcrumb

![menu - active copy](https://cloud.githubusercontent.com/assets/11636908/9528138/137366e6-4cc1-11e5-94f6-194db9e98266.png)
### Mobile header w/ breadcrumb

![mobile portrait copy 3](https://cloud.githubusercontent.com/assets/11636908/9528159/317954ca-4cc1-11e5-88e3-2ae996bab9ec.png)
### Mobile header w/ search

![mobile portrait copy 4](https://cloud.githubusercontent.com/assets/11636908/9528162/365b3832-4cc1-11e5-9393-69c90bb7d125.png)

**Comment by noahmanger** [comment]
Ok I took a first pass at this, but now I have some questions:
- I'm worried about replacing the glossary button with the search button on small screens. It raises a bunch of questions: does the search button only show when you're on the data side? How does the glossary work now? It feels weird to have a link in the menu activate a panel on the other side of the screen.
- That said, I'm a fan of losing the search box in the breadcrumbs on small screens, just because it will really take too much space. Maybe we just don't have it on those pages? Or maybe it lives in the menu dropdown?
- Last, what should we do about the "Beta" status? Maybe it's enough to just have it on the home page? I don't know.

**Comment by jenniferthibault** [comment]
I think we talked through the first two points the other day, but just to capture them here for clarity (and to make sure I came away with the correct info...)
- We drop the glossary icon from the top nav area entirely on mobile, since it could be a competing feature, instead of a helpful tool. glossary will still be accessible by tapping a word with the book icon, it just won't be in the top nav. Maybe it becomes an element in the footer nav?
- On mobile, the last view shown here is the search bar expanded—does that still make you think it's takes up too much space? regular view would only be the icon. Since on the desktop version, the search only appears in the data side (since there isn't universal search) it would keep stay consistent. (thoughts?)
- I think it's ok to drop "beta" status everywhere but the home page.
